### ISSUE TITLE
predict methods do not have probs option implemented

### ISSUE THREAD

**Issue by kbenoit** [jkrijthe/RSSL#10]
Looks like there is no use of the `probs` argument, for instance in https://github.com/jkrijthe/RSSL/blob/master/R/svmlin.R#L111-L123 

(as well as in most of the other predict methods).

**Comment by jkrijthe** [comment]
Yes, it seems I have been fairly inconsistent here: it only works for the LogisticRegression classifier. For others, when implemented, I used a separate method "posterior". So it would probably be best to remove these arguments everywhere, and add a posterior method to LogisticRegression

**Comment by jkrijthe** [comment]
Thanks for bringing this to my attention. I removed the probs arguments from the predict methods, and added a posterior method for the one case (LogisticRegression) where the probs argument was used.

**Comment by kbenoit** [comment]
Would it not be fairly straightforward to get probabilities from the decision values, using Platt scaling? This would be a nice option.

**Comment by jkrijthe** [comment]
Yes, that is what I would advise for those classifiers that do not currently have a posterior method. However, I have not implemented it as a default, since it is an additional choice that is not part of the classifiers themselves, and the unlabelled data would only be used to update the decision values, not in the estimation of the parameters of the Platt scaling (only indirectly through the updated decision values for the labeled objects).
