### ISSUE TITLE
question about evaluating the performance

### ISSUE THREAD

**Issue by xiuru** [jkrijthe/RSSL#6]
Hello jkrijthe,
I have some questions.
1. when i using 'CrossValidationSSL' to evaluating the performance, i can only use the labeled data to classify and run 'CrossValidationSSL' function? 
2.when i try the Examples after 'EMLeastSquaresClassifier',how can i plot when my dataset have many columns(The examples only have X1 X2 2 columns).
3.If i want to use both labeled and unlabeled datasets to classify, which kind of functions should i try and how can i evaluate the performance?

Thanks in advance.

**Comment by xiuru** [comment]
![image](https://user-images.githubusercontent.com/24283569/42187402-97ef7210-7e15-11e8-90e3-3bff1a60d4de.png)
I can perform method 'svmlin'.
But when i use method 'TSVM', i got this error: "argument 'X_u' is missing, with no default", when i have X_u matrix.
And Error in rep(C2, unlabelNum) : invalid 'times' argument when i try S4VM method.
Is my unlabeled matrix in correct format? How can i use these method?

**Comment by jkrijthe** [comment]
My attempt at some answers :-):

1. The CrossValidationSSL function in the package is used to evaluate different SSL methods by using a fully labeled dataset and removing some of the labels. So you have to give it a fully labeled dataset. If you want to do crossvalidation on labeled data while keeping the unlabeled set fixed, I would suggest sticking to the method you would normally use to do this (using the crossval, implementing your own solution, etc.)
2. The stat_classifier function currently is only implemented for 2D input spaces. I guess the code could be adapted to the more general setting where you set the remaining variables to a specific value.
3. Most implemented classifiers should be listed in the documentation in the See Also section of any of the classifiers. I now notice this is not the case for EMLeastSquaresClassifier, but the documentation of USMLeastSquaresClassifier is correct for instance. So that gives you a (partial list) of things to try. As for performance evaluation: this depends a bit on your setting, but you could split the labeled set into training and testing, or write a few lines of code using a package like crossval or caret to implement a crossvalidation procedure over the labeled data.

As for the error: SelfLearning expects method to be a supervised classifier (one that only uses labeled data), so TSVM would not work, but SVM, for instance, should.

**Comment by xiuru** [comment]
Thanks a lot for your detailed answer.
